networks:
  gitea:
    external: false

services:
  gitea:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    # restart: always
    networks:
      - gitea
    volumes:
      - ${MOUNTPATH}/gitea/data:/data
      # - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 2222:22
