services:
  youtrack:
    # https://hub.docker.com/r/jetbrains/youtrack/tags
    image: jetbrains/youtrack:2022.3.65371
    volumes:
      - ./mount/data:/opt/youtrack/data
      - ./mount/conf:/opt/youtrack/conf
      - ./mount/logs:/opt/youtrack/logs
      - ./mount/backups:/opt/youtrack/backups
    ports:
      - 8444:8080
